config/routes.rb
Rotas::Application.routes.draw do
  root :to => "home#index"

  match '/rotas/:url',             to: 'home#singlepage'
  match '/innovazione',             to: 'home#innovazione'
  match '/storia',                  to: 'home#storia'
  match '/company-profile',         to: 'home#company'
  match '/rotas-institute',         to: 'home#rotasinstitute'
  match '/bandi',                   to: 'home#bandi'
  match '/about',                   to: 'home#about'
  match '/produzione/:type',        to: 'home#produzione'
  match '/produzione/:sa/:type',    to: 'home#produzionefull'
  match '/portfolio/:type',         to: 'home#portfolio'
  match '/blog',                    to: 'home#blog'
  match '/contatti',                to: 'home#sendcontatti', via: :post
  match '/sendjob',                 to: 'home#sendjob',      via: :post
  match '/job',                     to: 'home#job'
  match '/clienti',                 to: 'home#clienti'
  match '/contact',                 to: 'home#contact'

  namespace :admin do
    root :to => "home#index"

    resources :sessions, only: [:create, :destroy]
    resources :static_pages, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :servizis
    resources :media, only: [:index, :create, :destroy]
    resources :video
    resource  :home

    match '/main',      to: 'home#main'
    match '/signin',    to: "sessions#new"
    match '/signout',   to: "sessions#destroy", via: :delete

    match '/static_pages/addmoduli/:id',    to: "static_pages#addmoduli"
    match '/static_pages/savemoduli',   to: "static_pages#savemoduli", via: :post
    match '/static_pages/updateorder',      to: "static_pages#updateorder"


    match '/servizis/deleteall',  to: "servizis#deleteall", via: :post

    # custom routes for mods management
    # category and sub-category management
    match '/mods',                to: "mods#index"
    match '/mods/addcat',         to: "mods#addcat"
    match '/mods/createcat',      to: "mods#createcat",     via: :post
    match '/mods/editcat',        to: "mods#editcat"
    match '/mods/updatecat',      to: "mods#updatecat",     via: :post
    match '/mods/destroycat',     to: "mods#destroycat",    via: :delete
    match '/mods/deleteallcat',   to: "mods#deleteallcat",  via: :post
    match '/mods/publishedcat',   to: "mods#publishedcat"
    match '/mods/updateorder',    to: "mods#updateorder",   via: :post

    # leaf management
    match '/mods/list',             to: "mods#list"
    match '/mods/addele',           to: "mods#addele"
    match '/mods/createele',        to: "mods#createele",         via: :post
    match '/mods/editele',          to: "mods#editele"
    match '/mods/updateele',        to: "mods#updateele",         via: :post
    match '/mods/destroyele',       to: "mods#destroyele",        via: :delete
    match '/mods/deleteallele',     to: "mods#deleteallele",      via: :post
    match '/mods/associafile',      to: "mods#associafile",       via: :post
    match '/mods/destroyimages',    to: "mods#destroyimages",     via: :post
    match '/mods/destroyallimages', to: "mods#destroyallimages",  via: :delete
    match '/mods/updateimagetext',  to: "mods#updateimagetext",   via: :post
    match '/mods/publishedele',     to: "mods#publishedele"
    match '/mods/updateorderele',   to: "mods#updateorderele",    via: :post

    match '/mods/associavideo',     to: "mods#associavideo",      via: :post
    match '/mods/destroyvideo',     to: "mods#destroyvideo",      via: :post
    match '/mods/destroyallvideo',  to: "mods#destroyallvideo",   via: :delete
    match '/mods/updatevideotext',  to: "mods#updatevideotext",   via: :post


    # media management
    match '/media/destroyall',          to: "media#destroyall",         via: :post
    match '/media/create_categoria',    to: "media#create_categoria",   via: :post
    match '/media/delcat',              to: "media#delcat",             via: :post
    match '/media/movecat',             to: "media#movecat",            via: :post
    match '/media/associa',             to: "media#associa"
    match '/media/associafile',         to: "media#associafile",       via: :post
    match '/media/destroyimages',       to: "media#destroyimages",     via: :post
    match '/media/destroyallimages',    to: "media#destroyallimages",  via: :delete
    match '/media/updateimagetext',     to: "media#updateimagetext",   via: :post
    match '/media/updateordermedia',    to: "media#updateordermedia",  via: :post
    match '/media/getfile',             to: "media#getfile"

    # video management
    match '/video/update',            to: "video#update",           via: :post
  end
end

app/views/admin/partials/_editor.html.erb
<!--
  MODAL DIALOG FOR FILES LIST
-->
<div class="modal hide fade" id="upload-modal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4>File caricati nel sistema</h4>
  </div>
  <div class="modal-body">
    <p>
      Clicca su di un file qui sotto per caricarlo nell'editor
      <br/>
      <ul class="thumbnails">
        <% @upload.each do |file| %>
        <li class="span2">
          <a href="#" id="image-<%= file.id %>" rel='http://localhost:3000/<%= file.filename %>'>
            <div class="thumbnail">
              <%= image_tag file.filename_url(:micro), :class => "img-polaroid" %>
            </div>
          </a>
        </li>
        <% end %>
      </ul>
    </p>
  </div>
  <div class="modal-footer">
    <input type="hidden" id="source-editor" />
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>
<!--
  END MODAL DIALOG FOR FILES LIST
-->


<script type="text/javascript">
	$(document).ready(function(){
		$("#upload-modal").modal('hide')

	  $("a[id^='image-']").click(function() {
	    var editor = $( "#"+$("#source-editor").val() ).data("kendoEditor")
	    editor.paste('<img src="'+ $(this).attr("rel") +'" />' )
	    $("#upload-modal").modal('hide')
	  });

		editor_tools = [
			"bold",
			"italic",
			"underline",
			"fontName",
			"fontSize",
			"foreColor",
			"backColor",
			"justifyLeft",
			"justifyCenter",
			"justifyRight",
			"justifyFull",
			"insertUnorderedList",
			"insertOrderedList",
			"indent",
			"outdent",
			"formatBlock",
			"createLink",
			"unlink",
			"viewHtml",
			{
				name: "selectImage",
				icon: "insertImage",
				tooltip: "Seleziona una immagine da quelle precedentemente caricate",
				exec: function (e) {
					$("#source-editor").val($(this).attr("id"));
					$("#upload-modal").modal('show');
				}
			}
    ]

		$(".editor").kendoEditor({
			encoded:false,
			tools: editor_tools,
		});

		$(".date").kendoDatePicker({
			format: "dd/MM/yyyy",
			culture: "it-IT"
		});

	});	
</script>

<style type="text/css">
	.k-selectImage {
  	background: transparent url(<%= asset_path 'Metro/sprite.png' %>) no-repeat -116px -88px;
  }
  .date {
  	height:35px;
  }
</style>

app/views/admin/partials/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/partials/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://arealabz.it/">AreaLabz</a>
  </small>
</footer>

app/views/admin/partials/_header.html.erb
<div class="row-fluid">
  <header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= image_tag "simbolo.png", :style => "float:left;margin-right:20px; " %><%= link_to "Admin", '/admin', id: "logo" %>
        <nav>
          <ul class="nav pull-right">
            <li><%= link_to raw("<i class='icon-home icon-white'></i>&nbsp;&nbsp;Home"), admin_root_path %></li>
            <% if signed_in? %>
              <li class="dropdown">
                <a href="#menu-media" class="dropdown-toggle" data-toggle="dropdown" >
                  <i class="icon-picture icon-white"></i>&nbsp;&nbsp;Gestione Media
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to raw("<i class='icon-camera'></i>&nbsp;&nbsp;Gestione Immagini"), admin_media_path %></li>
                  <!-- <li><%= link_to raw("<i class='icon-play-circle'></i>&nbsp;&nbsp;Gestione Video"), admin_video_index_path %></li>     -->
                </ul>
              </li>
              <li><%= link_to raw("<i class='icon-picture icon-white'></i>&nbsp;&nbsp;Gestione Pagine Statiche"), admin_static_pages_path %></li>
              <li class="dropdown" id="menu-servizi">
                <a href="#menu-servizi" class="dropdown-toggle" data-toggle="dropdown" >
                  <i class="icon-cog icon-white"></i>&nbsp;&nbsp;Gestione Servizi
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <% if administrator? %>
                    <li><%= link_to raw("<i class='icon-book'></i>&nbsp;&nbsp;Servizi"), admin_servizis_path %></li>
                    <li class="divider"></li>
                  <% end %>
                  <% @all_servizi.each do |servizio| %>
                    <li><%= link_to raw("<i class='icon-list'></i>&nbsp;&nbsp;#{servizio.label}"), servizio.path %></li>
                  <% end %>
                </ul>
              </li>
              <li><%= link_to raw("<i class='icon-off icon-white'></i>&nbsp;&nbsp;Logout"), admin_signout_path, method: "delete" %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </header>
</div>

app/views/admin/partials/_media_manager.html.erb
<div class="row-fluid">
  <div class="span12">
    <h3 style="text-align:right;margin-bottom:5px;">Gestione Immagini Predefinite</h3>
    <ul class="nav nav-tabs nav-stacked">
      <% if @ele.nil? %>
        <li><a href="#">Salva prima il contenuto dell'elemento per poi potergli associare le immagini</a></li>
      <% else %>
        <li>
        	<a href="#" id="sel-file">Seleziona/Modifica i file da associare all'elemento</a>
        	<br/>
          <div style="width:100%;margin-bottom:20px;" id="file-box">
            <% @ele.upload.each do |up| %>
              <div style="width:30%;float:left;margin-bottom:20px;">
                <% if up.ext =~ /image/ %>
                  <%= image_tag up.filename_url(:micro), :class => "img-polaroid" %>
                <% else %>
                  <%= image_tag "file_pdf.png", :class => "img-polaroid" %>
                <% end %>
              </div>
              <div style="width:70%;float:right;margin-bottom:20px;">
                <textarea id="text-<%= up.id %>" name="text-<%= up.id %>" style="width:100%;height:50px;"><%= get_media_description(@ele,up)%></textarea>
                <br/>
                <input type="checkbox" name="rimuovi" id="remove-<%= up.id %>" value="<%= up.id %>" /> 
                <%= truncate(print_file_name(up.filename_url), :length => 70) %>
              </div>
              <div style="clear:both"></div>
            <% end %>
          </div>
        </li>
      <% end %>
      <li id="eliminazione-file">
        <% if !@ele.nil? && @ele.upload.count > 0 %>
        	<a href="#" id="elimina-immagini">Elimina immagini selezionate</a>
          <%= link_to raw("Elimina tutte le immagini"), "/admin/mods/destroyallimages?idserv=#{@servizio.id}&idc=#{@ele.fkcat}&id=#{@ele.id}", method: :delete, data: { confirm: "Sei sicuro di voler eliminare tutte le immagini?" }  %>
        <% end %>
      </li>
   	</ul>
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    <h3 style="text-align:right;margin-bottom:5px;">Gestione Video</h3>
    <ul class="nav nav-tabs nav-stacked">
      <% if @ele.nil? %>
        <li><a href="#">Salva prima il contenuto dell'elemento per poi potergli associare i video</a></li>
      <% else %>
        <li>
          <a href="#" id="sel-video">Seleziona/Modifica i video da associare all'elemento</a>
          <br/>
          <div style="width:100%;margin-bottom:20px;" id="video-box">
            <% @ele.video.each do |up| %>
              <div style="width:30%;float:left;margin-bottom:20px;">
                <%= image_tag up.img, :class => "img-polaroid", :width => "80", :height => "80" %>
              </div>
              <div style="width:70%;float:right;margin-bottom:20px;">
                <textarea id="videotext-<%= up.id %>" name="videotext-<%= up.id %>" style="width:100%;height:50px;"><%= get_video_description(@ele,up)%></textarea>
                <br/>
                <input type="checkbox" name="rimuovi" id="remove-<%= up.id %>" value="<%= up.id %>" /> 
                <%= truncate(print_file_name(up.title), :length => 70) %>
              </div>
              <div style="clear:both"></div>
            <% end %>
          </div>
        </li>
      <% end %>
      <li id="eliminazione-video">
        <% if !@ele.nil? && @ele.video.count > 0 %>
          <a href="#" id="elimina-video">Elimina video selezionate</a>
          <%= link_to raw("Elimina tutte le immagini"), "/admin/mods/destroyallvideo?idserv=#{@servizio.id}&idc=#{@ele.fkcat}&id=#{@ele.id}", method: :delete, data: { confirm: "Sei sicuro di voler eliminare tutti i video?" }  %>
        <% end %>
      </li>
    </ul>
  </div>
</div>  

<!--
  MODAL DIALOG FOR FILES LIST
-->
<div class="modal hide fade" id="media-modal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4>File caricati nel sistema</h4>
  </div>
  <div class="modal-body">
    <p>
      Seleziona i file che desideri associare
      <br/>
      <ul class="thumbnails">
        <% @upload.each do |up| %>
        <li class="span2">
          <div class="thumbnail">
            <% if up.ext =~ /image/ %>
              <%= image_tag up.filename_url(:micro), :class => "img-polaroid" %>
            <% else %>
              <%= image_tag "file_pdf.png", :class => "img-polaroid" %>
            <% end %>
            <br>
            <% check = "" %>
            <% if !@m_array.nil? && (@m_array.include? up.id) %>
              <% check = "checked='checked'" %>
            <% end %>
            <input type="checkbox" <%= check %> name="rimuovi" id="modal-<%= up.id %>" value="<%= up.id %>" /> 
            <%= truncate(print_file_name(up.filename_url), :length => 10) %>
          </div>
        </li>
        <% end %>
      </ul>
    </p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
    <a href="#" class="btn btn-primary" id="associa-file">Associa file</a>
  </div>
</div>
<!--
  END MODAL DIALOG FOR FILES LIST
-->


<!--
  MODAL DIALOG FOR VIDEO LIST
-->
<div class="modal hide fade" id="video-modal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4>Video caricati nel sistema</h4>
  </div>
  <div class="modal-body">
    <p>
      Seleziona i video che desideri associare
      <br/>
      <ul class="thumbnails">
        <% @video.each do |up| %>
        <li class="span2">
          <div class="thumbnail">
            <%= image_tag up.img, :class => "img-polaroid" %>
            <br>
            <% check = "" %>
            <% if !@m_array.nil? && (@m_array.include? up.id) %>
              <% check = "checked='checked'" %>
            <% end %>
            <input type="checkbox" <%= check %> name="rimuovi" id="video-<%= up.id %>" value="<%= up.id %>" /> 
            <%= truncate(up.title, :length => 10) %>
          </div>
        </li>
        <% end %>
      </ul>
    </p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
    <a href="#" class="btn btn-primary" id="associa-video">Associa video</a>
  </div>
</div>
<!--
  END MODAL DIALOG FOR VIDEO LIST
-->

<script type="text/javascript">

	$(document).ready(function() {
    $("[id^='videotext']").focusout(function() {
      var id = $(this).attr("id").split("-")[1]
      
      $.post("/admin/mods/updatevideotext", {"id": id, "text": $(this).val(), "ide": "<%= @ele.id unless @ele.nil? %>"}, function () {});
    });

		$("#media-modal").modal('hide');

		$("#sel-file").click(function() {
			$("#media-modal").modal('show')
		});

		$("#associa-file").click(function() {
			var add_elements = new Array();
      var result = $("input[id^='modal-']").each(function(){
        if ( $(this).is(":checked") ) {
          add_elements.push($(this).val());
        }
      });
      var string_result = add_elements.join(",");
      
      $.post("/admin/mods/associafile", {"id": ""+ string_result +"", "ide": "<%= @ele.id unless @ele.nil? %>"}, function(txt) {
      	$("#file-box").html(txt.txt);
        $("#eliminazione-file").html(txt.del)
        $("#media-modal").modal('hide');

        $("[id^='text']").focusout(function() {
          var id = $(this).attr("id").split("-")[1]
          
          $.post("/admin/mods/updateimagetext", {"id": id, "text": $(this).val(), "ide": "<%= @ele.id unless @ele.nil? %>"}, function () {});
        });

        $("#elimina-immagini").click(function() {
          if (window.confirm("Eliminare le immagini selezionate?")) {
            var add_elements = new Array();
            var result = $("input[id^='remove-']").each(function(){
              if ( $(this).is(":checked") ) {
                add_elements.push($(this).val());
              }
            });
            var string_result = add_elements.join(",");
            
            $.post("/admin/mods/destroyimages", {"id": ""+ string_result +"", "ide": "<%= @ele.id unless @ele.nil? %>"}, function(txt) {
              document.location = "/admin/mods/editele?idserv=<%= @servizio.id %>&idc=<%= @ele.fkcat  unless @ele.nil? %>&id=<%= @ele.id  unless @ele.nil? %>"
            });
          }
        });
      });
		});

    $("#elimina-immagini").click(function() {
      if (window.confirm("Eliminare le immagini selezionate?")) {
        var add_elements = new Array();
        var result = $("input[id^='remove-']").each(function(){
          if ( $(this).is(":checked") ) {
            add_elements.push($(this).val());
          }
        });
        var string_result = add_elements.join(",");
        
        $.post("/admin/mods/destroyimages", {"id": ""+ string_result +"", "ide": "<%= @ele.id unless @ele.nil? %>"}, function(txt) {
          document.location = "/admin/mods/editele?idserv=<%= @servizio.id %>&idc=<%= @ele.fkcat  unless @ele.nil? %>&id=<%= @ele.id  unless @ele.nil? %>"
        });
      }
    });

    $("#sel-video").click(function() {
      $("#video-modal").modal('show')
    }); 

    $("#associa-video").click(function() {
      var add_elements = new Array();
      var result = $("input[id^='video-']").each(function(){
        if ( $(this).is(":checked") ) {
          add_elements.push($(this).val());
        }
      });
      var string_result = add_elements.join(",");
      
      $.post("/admin/mods/associavideo", {"id": ""+ string_result +"", "ide": "<%= @ele.id unless @ele.nil? %>"}, function(txt) {
        $("#video-box").html(txt.txt);
        $("#eliminazione-video").html(txt.del)
        $("#video-modal").modal('hide');

        $("[id^='videotext']").focusout(function() {
          var id = $(this).attr("id").split("-")[1]
          
          $.post("/admin/mods/updatevideotext", {"id": id, "text": $(this).val(), "ide": "<%= @ele.id unless @ele.nil? %>"}, function () {});
        });

        $("#elimina-video").click(function() {
          if (window.confirm("Eliminare i video selezionati?")) {
            var add_elements = new Array();
            var result = $("input[id^='remove-']").each(function(){
              if ( $(this).is(":checked") ) {
                add_elements.push($(this).val());
              }
            });
            var string_result = add_elements.join(",");
            
            $.post("/admin/mods/destroyvideo", {"id": ""+ string_result +"", "ide": "<%= @ele.id unless @ele.nil? %>"}, function(txt) {
              document.location = "/admin/mods/editele?idserv=<%= @servizio.id %>&idc=<%= @ele.fkcat  unless @ele.nil? %>&id=<%= @ele.id  unless @ele.nil? %>"
            });
          }
        });
      });
    });


	}); 
</script>

app/views/admin/partials/_mod_manager.html.erb
<div class="span3">
  <h3 style="text-align:right;margin-bottom:5px;">Gestione Moduli</h3>
  <ul class="nav nav-tabs nav-stacked">
    <li>
    	<a href="#" id="sel-file">Seleziona i moduli da associare alla pagina statica</a>
    </li>
		<% rel_cat_arr = @static.related_cat.split(",") unless @static.related_cat.nil? %>
    <% @sel_cat.each do |cat| %>
      <li>
        <a href="#">
          <label class="checkbox">
            <input type="checkbox" <%= "checked" if rel_cat_arr && rel_cat_arr.include?(cat[1].to_s) %> name="moduli[<%= cat[1] %>]" value="<%= cat[1] %>" />&nbsp;<%= cat[0] %>
          </label>
        </a>
      </li>
    <% end %>
  </ul>
</div>

<script type="text/javascript">
	$(document).ready(function() {
	}); 
</script>

app/views/admin/partials/_shims.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->