config/routes.rb
Rotas::Application.routes.draw do
  root :to => "home#index"

  match '/rotas/:url',             to: 'home#singlepage'
  match '/innovazione',             to: 'home#innovazione'
  match '/storia',                  to: 'home#storia'
  match '/company-profile',         to: 'home#company'
  match '/rotas-institute',         to: 'home#rotasinstitute'
  match '/bandi',                   to: 'home#bandi'
  match '/about',                   to: 'home#about'
  match '/produzione/:type',        to: 'home#produzione'
  match '/produzione/:sa/:type',    to: 'home#produzionefull'
  match '/portfolio/:type',         to: 'home#portfolio'
  match '/blog',                    to: 'home#blog'
  match '/contatti',                to: 'home#sendcontatti', via: :post
  match '/sendjob',                 to: 'home#sendjob',      via: :post
  match '/job',                     to: 'home#job'
  match '/clienti',                 to: 'home#clienti'
  match '/contact',                 to: 'home#contact'

  namespace :admin do
    root :to => "home#index"

    resources :sessions, only: [:create, :destroy]
    resources :static_pages, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :servizis
    resources :media, only: [:index, :create, :destroy]
    resources :video
    resource  :home

    match '/main',      to: 'home#main'
    match '/signin',    to: "sessions#new"
    match '/signout',   to: "sessions#destroy", via: :delete

    match '/static_pages/addmoduli/:id',    to: "static_pages#addmoduli"
    match '/static_pages/savemoduli',   to: "static_pages#savemoduli", via: :post
    match '/static_pages/updateorder',      to: "static_pages#updateorder"


    match '/servizis/deleteall',  to: "servizis#deleteall", via: :post

    # custom routes for mods management
    # category and sub-category management
    match '/mods',                to: "mods#index"
    match '/mods/addcat',         to: "mods#addcat"
    match '/mods/createcat',      to: "mods#createcat",     via: :post
    match '/mods/editcat',        to: "mods#editcat"
    match '/mods/updatecat',      to: "mods#updatecat",     via: :post
    match '/mods/destroycat',     to: "mods#destroycat",    via: :delete
    match '/mods/deleteallcat',   to: "mods#deleteallcat",  via: :post
    match '/mods/publishedcat',   to: "mods#publishedcat"
    match '/mods/updateorder',    to: "mods#updateorder",   via: :post

    # leaf management
    match '/mods/list',             to: "mods#list"
    match '/mods/addele',           to: "mods#addele"
    match '/mods/createele',        to: "mods#createele",         via: :post
    match '/mods/editele',          to: "mods#editele"
    match '/mods/updateele',        to: "mods#updateele",         via: :post
    match '/mods/destroyele',       to: "mods#destroyele",        via: :delete
    match '/mods/deleteallele',     to: "mods#deleteallele",      via: :post
    match '/mods/associafile',      to: "mods#associafile",       via: :post
    match '/mods/destroyimages',    to: "mods#destroyimages",     via: :post
    match '/mods/destroyallimages', to: "mods#destroyallimages",  via: :delete
    match '/mods/updateimagetext',  to: "mods#updateimagetext",   via: :post
    match '/mods/publishedele',     to: "mods#publishedele"
    match '/mods/updateorderele',   to: "mods#updateorderele",    via: :post

    match '/mods/associavideo',     to: "mods#associavideo",      via: :post
    match '/mods/destroyvideo',     to: "mods#destroyvideo",      via: :post
    match '/mods/destroyallvideo',  to: "mods#destroyallvideo",   via: :delete
    match '/mods/updatevideotext',  to: "mods#updatevideotext",   via: :post


    # media management
    match '/media/destroyall',          to: "media#destroyall",         via: :post
    match '/media/create_categoria',    to: "media#create_categoria",   via: :post
    match '/media/delcat',              to: "media#delcat",             via: :post
    match '/media/movecat',             to: "media#movecat",            via: :post
    match '/media/associa',             to: "media#associa"
    match '/media/associafile',         to: "media#associafile",       via: :post
    match '/media/destroyimages',       to: "media#destroyimages",     via: :post
    match '/media/destroyallimages',    to: "media#destroyallimages",  via: :delete
    match '/media/updateimagetext',     to: "media#updateimagetext",   via: :post
    match '/media/updateordermedia',    to: "media#updateordermedia",  via: :post
    match '/media/getfile',             to: "media#getfile"

    # video management
    match '/video/update',            to: "video#update",           via: :post
  end
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
	has_many :sml, :class_name => "StaticPageSml", :foreign_key => "static_page_id"
  mount_uploader :foto, PicUploader
  mount_uploader :foto_home, PicUploader

  accepts_nested_attributes_for :sml, :allow_destroy => true

  default_scope order: 'ordine'
  
  def get_nome_pagina(id)
  	pagina = self.find(id)
  	
  	pagina.sml.where("fklang=?", "it").first.title
  end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < Admin::AdminController
  before_filter :signed_in_user
  before_filter {
    @lingue   = Lingue.where("active=?", "1").order("id")
  }

  def index
    @static = StaticPage.where("f_del=?", "0")
  end

  def new
    @static = StaticPage.new
    static_sml = @static.sml.build
    @lingue.each do |lang|
      @sml = {lang.cod => nil}
    end

    cats = ModCat.fetchAllCatForServizi
    @sel_cat = generateSelectFromCats cats
  end

  def create
    gen = (true && params[:static_page]) || {}
    gen['f_del'] = 0

    unless params['moduli'].nil?
      str_cat = params['moduli'].keys.join(",")
    else 
      str_cat = ""
    end
    gen['related_cat'] = str_cat

    logger.info gen.inspect

    @static = StaticPage.new(gen)
    if @static.save
      @lingue.each do |lang|
        lingua = params[lang.cod]
        lingua['fklang'] = lang.cod
        lingua['static_page_id'] = @static.id

        #@static.static_page_sml.create(lingua)
        static_sml = StaticPageSml.new(lingua)
        if static_sml.save
          flash[:notice] = "Pagina statica salvata con successo"
          redirect_to admin_static_pages_path
        else
          render 'new'
        end
      end
    end
  end

  def edit
    @static = StaticPage.find(params[:id])

    @sml = {}
    @lingue.each do |lang|
      sml_ele = @static.sml.where('fklang=? AND static_page_id=?', lang.cod, @static.id).first
      @sml = {lang.cod => sml_ele}
    end

    cats = ModCat.fetchAllCatForServizi
    @sel_cat = generateSelectFromCats cats
  end

  def update
    @static = StaticPage.find(params[:id])

    gen = (true && params[:static_page]) || {}
    gen['f_del'] = 0

    unless params['moduli'].nil?
      str_cat = params['moduli'].keys.join(",")
    else 
      str_cat = ""
    end
    gen['related_cat'] = str_cat

    if @static.update_attributes(gen)
      @lingue.each do |lang|
        lingua = params[lang.cod]
        lingua['fklang'] = lang.cod
        lingua['static_page_id'] = @static.id

        sml_mod = @static.sml.where('fklang=? AND static_page_id=?', lang.cod, @static.id).first
        if !sml_mod.nil?
          if sml_mod.update_attributes(lingua)
            flash[:notice] = 'Elemento aggiornato con successo.'
          else
            error = true
          end
        else
          sml_mod = ModulesCatSml.new(lingua)
          if sml_mod.save
            flash[:notice] = 'Elemento aggiornato con successo.'
          else
            error = true
          end
        end

        render 'edit' if error
      end
    end

    redirect_to admin_static_pages_path     
  end

  def destroy
    StaticPage.find(params[:id]).update_attributes({"f_del" => "1"})
    flash[:success] = "Pagina statica eliminata con successo."
    redirect_to admin_static_pages_path
  end

=begin
  def published
    @static = StaticPage.find(params[:id])

    if @static.published == 1
      @static.update_attributes({"published" => 0})
    else
      @static.update_attributes({"published" => 1})
    end

    redirect_to admin_static_pages_path
  end
=end

  def updateorder
    x = 1
    order_arr = params[:id].split(',')

    order_arr.each_with_index do |id, index|
      #logger.info "#{id} --> #{index}"
      order = {"ordine" => index + 1}

      mod = StaticPage.find(id.to_i)
      mod.update_attributes(order)
    end

    render :nothing => true
  end

  def addmoduli
    cats = ModCat.fetchAllCatForServizi
    @sel_cat = generateSelectFromCats cats
    @pagina = StaticPage.find(params[:id])

    render :layout => 'empty'
  end

  def savemoduli
    @pagina = StaticPage.find(params['id'])
    unless params['moduli'].nil?
      str_cat = params['moduli'].keys.join(",")
    else 
      str_cat = ""
    end

    @pagina.update_attributes({:related_cat => str_cat })
    cats = ModCat.fetchAllCatForServizi
    @sel_cat = generateSelectFromCats cats

    render 'addmoduli', :layout => 'empty'
  end

  private
    def correct_user
      @user = User.find(params[:id])
      redirect_to(admin_root_path) unless current_user?(@user)
    end

    def generateSelectFromCats(cats) 
      result = []
      cats.each do |cat|
        obj = [ cat['sml']['it'].title, cat['gen'].id ]
        result.push obj
      end

      result
    end

end

app/helpers/admin/static_pages_helper.rb
module Admin::StaticPagesHelper
end

app/views/admin/static_pages/_form.html.erb
<div class="row-fluid">
	<div class="span9">
		<div class="control-group">
			<label for="static_image" class="control-label">Immagine Principale</label>
			<div class="controls">
				<%= f.file_field :foto %>
				<br/><br/>
				<%= (image_tag @static.foto_url(:thumb)) if !@static.foto_url(:thumb).nil? %>
				<br>
				<% unless @static.foto_url(:thumb).nil? %>
					<label class="checkbox"><%= f.check_box :remove_foto %> Elimina immagine</label>
				<% end %>
			</div>
		</div>

		<ul id="tabs" class="nav nav-tabs">
			<% @lingue.each do |lingua| %>
				<li class="<%= "active" if lingua.cod.eql?('it') %>"><a href="#<%= lingua.cod %>"><%= lingua.lingua %></a></li>
			<% end %>
		</ul>
		<div class="tab-content">
			<% @lingue.each do |lingua| %>

				<% ele = @sml[lingua.cod] %>

				<div id="<%= lingua.cod %>" class="tab-pane <%= "active" if lingua.cod.eql?('it') %>">

					<div class="control-group">
						<label for="<%= lingua.cod %>_titolo" class="control-label">Titolo (<%= lingua.cod %>)</label>
						<div class="controls">
							<input type="text" name="<%= lingua.cod %>[title]" id="<%= lingua.cod %>_titolo" class="input-xlarge" value="<%= ele.title unless ele.nil? %>">
						</div>
					</div>

					<div class="control-group">
						<label for="<%= lingua.cod %>_testo" class="control-label">Testo (<%= lingua.cod %>)</label>
						<div class="controls">
							<textarea name="<%= lingua.cod %>[testo]" id="<%= lingua.cod %>_testo" class="input-xlarge editor"><%= ele.testo unless ele.nil? %></textarea>
						</div>
					</div>

				</div>
			<% end %>
		</div>
	</div>

	<%#= render 'admin/partials/mod_manager' %>
</div>
<script type="text/javascript">

$(window).ready(function() {
	$(".editor").kendoEditor({
		encoded:false
	});

	$('#tabs a').click(function (e) {
  	e.preventDefault();
  	$(this).tab('show');
	});

});
</script>

app/views/admin/static_pages/_lang_field.html.erb
<%= f.label :title, "Titolo" %><br />
<%= f.text_field :title  %>

app/views/admin/static_pages/addmoduli.html.erb
<div class="row-fluid">
	<div class="span12">
		<h2>Seleziona i moduli da associare alla pagina <strong>"<%= @pagina.sml.where("fklang=?", "it").first.title %>"</strong></h2>
	</div>

	<form action="/admin/static_pages/savemoduli" class="form-horizontal" method="post">
		<input type="hidden" name="id" value="<%= @pagina.id %>">
		<div class="span12">
			<% rel_cat_arr = @pagina.related_cat.split(",") unless @pagina.related_cat.nil? %>
			<% @sel_cat.each do |cat| %>
				<div class="span4">
					<input type="checkbox" <%= "checked" if rel_cat_arr && rel_cat_arr.include?(cat[1].to_s) %> name="moduli[<%= cat[1] %>]" value="<%= cat[1] %>" class="checkbox" />&nbsp;<%= cat[0] %>
				</div>
			<% end %>
		</div>
		<div class="span12" style="text-align:right;margin-top:30px;">
			<input type="submit" class="btn btn-default" value="Salva Associazioni">
		</div>
	</form>
</div>

app/views/admin/static_pages/edit.html.erb
<script type="text/javascript">
	$(document).ready(function() {
		//$("#tabs").tab('show');
	});
</script>
<ul class="breadcrumb">
  <li>
    <%= link_to "Pagine Statiche", admin_static_pages_path %>
    <span class="divider"></span>
    Inserimento / Modifica
  </li>
</ul>

<div class="row-fluid">
	<div class="span12">
		
		<%= form_for [:admin, @static], :html => {:id => "form", :class => "form-horizontal", :multipart => true} do |f| %>

			<%= render :partial => 'admin/static_pages/form', :locals => { :f => f } %>

			<div class="span12">
				<div class="form-actions">
					<%= f.submit "save", :class => "btn btn-primary" %>
					<%= f.submit "cancel", :class => "btn" %>
				</div>	
			</div>
		<% end %>
		
	</div>
</div>

app/views/admin/static_pages/index.html.erb
<ul class="breadcrumb">
  <li>
    <%= link_to "Pagine Statiche", admin_static_pages_path %><span class="divider"></span>
  </li>
</ul>

<%#= breadcrumb(@servizio.id, @id_parent) %>
<%= link_to raw("Aggiungi <i class='icon-plus-sign icon-white'></i>"), new_admin_static_page_path, class: "btn btn-small btn-primary new-button" %>

<br/>
<br/>
<table class="table table-striped table-bordered table-condensed admin-table" id="sort">
  <thead>
    <th width="5%">#</th>
    <th width="75%">Pagina</th>
    <th width="10%">Operazioni</th>
  </thead>
  <tbody>
    <% @static.each do |pagina| %>
    <tr id="<%= pagina.id %>">
      <td style="text-align:center"><i class="icon-move"></i></td>
      <td><%= pagina.sml.where("fklang=?", "it").first.title %></td>
      <td style="text-align:center">
        <%= link_to raw("<i class='icon-list-alt'></i>"), edit_admin_static_page_path(pagina), :rel => "operazioni_#{pagina.id}", :title => "Modifica #{pagina.
          sml.where('fklang=?', 'it').first.title}" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
  $(document).ready(function() {
    $("a[rel^='operazioni']").tooltip({'placement':'left'});

    $("#sort tbody").sortable({
      items: "tr",
      stop: function(event, ui) {
          var result = $(this).sortable('toArray');
          var string_result = result.join(",");
          
          $.post("/admin/static_pages/updateorder/", {id: ""+ string_result +""}, function(txt) { 
            location.reload();
          })
        }
    }); 
    $("#sort tbody").disableSelection();
  });
</script>

app/views/admin/static_pages/new.html.erb
<script type="text/javascript">
	$(document).ready(function() {
		//$("#tabs").tab('show');
	});
</script>
<ul class="breadcrumb">
  <li>
    <%= link_to "Pagine Statiche", admin_static_pages_path %>
    <span class="divider"></span>
    Inserimento / Modifica
  </li>
</ul>

<div class="row-fluid">
	<div class="span12">
		
		<%= form_for [:admin, @static], :html => {:id => "form", :class => "form-horizontal", :multipart => true} do |f| %>

			<%= render :partial => 'admin/static_pages/form', :locals => { :f => f } %>

			<div class="span12">
				<div class="form-actions">
					<%= f.submit "save", :class => "btn btn-primary" %>
					<%= f.submit "cancel", :class => "btn" %>
				</div>	
			</div>

		<% end %>
		
	</div>
</div>